ALTER TYPE "IntegrationStatus" ADD VALUE IF NOT EXISTS 'NOT_CONFIGURED';
ALTER TYPE "IntegrationStatus" ADD VALUE IF NOT EXISTS 'AUTH_FAILED';
ALTER TYPE "IntegrationStatus" ADD VALUE IF NOT EXISTS 'ERROR';
